
import { serve } from "https://deno.land/std@0.190.0/http/server.ts";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { reportData, format, timeframe } = await req.json();

    if (format === 'csv') {
      const csvContent = generateCSV(reportData);
      return new Response(csvContent, {
        headers: {
          'Content-Type': 'text/csv',
          'Content-Disposition': `attachment; filename="phishing-report-${new Date().toISOString().split('T')[0]}.csv"`,
          ...corsHeaders
        }
      });
    } else if (format === 'pdf') {
      // For PDF generation, you would typically use a library like jsPDF or puppeteer
      // For now, returning a simple text-based report
      const textReport = generateTextReport(reportData, timeframe);
      return new Response(textReport, {
        headers: {
          'Content-Type': 'text/plain',
          'Content-Disposition': `attachment; filename="phishing-report-${new Date().toISOString().split('T')[0]}.txt"`,
          ...corsHeaders
        }
      });
    }

    return new Response('Unsupported format', { status: 400 });

  } catch (error) {
    console.error('Export error:', error);
    return new Response(
      JSON.stringify({ error: 'Failed to export report' }),
      {
        status: 500,
        headers: { 
          'Content-Type': 'application/json',
          ...corsHeaders 
        }
      }
    );
  }
});

function generateCSV(reportData: any): string {
  let csv = 'Campaign Name,Emails Sent,Opened,Clicked,Submitted,Reported\n';
  
  reportData.campaignData.forEach((campaign: any) => {
    csv += `"${campaign.name}",${campaign.sent},${campaign.opened},${campaign.clicked},${campaign.submitted},${campaign.reported}\n`;
  });

  csv += '\n\nDepartment Analysis\n';
  csv += 'Department,Emails Sent,Opened,Clicked,Submitted,Vulnerability Score\n';
  
  reportData.departmentData.forEach((dept: any) => {
    csv += `"${dept.department}",${dept.sent},${dept.opened},${dept.clicked},${dept.submitted},${dept.vulnerability_score}%\n`;
  });

  return csv;
}

function generateTextReport(reportData: any, timeframe: string): string {
  const date = new Date().toLocaleDateString();
  
  return `
PHISHING SIMULATION REPORT
Generated: ${date}
Timeframe: Last ${timeframe} days

=== OVERVIEW ===
Total Campaigns: ${reportData.overallMetrics.totalCampaigns}
Total Emails Sent: ${reportData.overallMetrics.totalEmailsSent}
Average Open Rate: ${reportData.overallMetrics.averageOpenRate}%
Average Click Rate: ${reportData.overallMetrics.averageClickRate}%
Average Submit Rate: ${reportData.overallMetrics.averageSubmitRate}%
Average Report Rate: ${reportData.overallMetrics.averageReportRate}%

=== CAMPAIGN PERFORMANCE ===
${reportData.campaignData.map((campaign: any) => 
  `${campaign.name}: ${campaign.sent} sent, ${campaign.opened} opened (${Math.round((campaign.opened/campaign.sent)*100)}%), ${campaign.clicked} clicked (${Math.round((campaign.clicked/campaign.sent)*100)}%)`
).join('\n')}

=== DEPARTMENT ANALYSIS ===
${reportData.departmentData.map((dept: any) => 
  `${dept.department}: ${dept.sent} targets, ${dept.vulnerability_score}% vulnerability score`
).join('\n')}

=== RECOMMENDATIONS ===
- Focus additional training on departments with high vulnerability scores
- Consider more frequent simulations for high-risk groups
- Analyze common patterns in successful phishing attempts
- Implement targeted awareness campaigns based on department performance

Report generated by Phishing Simulation Guardian
  `;
}
