-- Create architecture_plans table for dynamic Flutter UI architecture planning
-- This table stores comprehensive architecture plans generated by the Architecture Decision Engine

-- Create enums for architecture plan categorization
CREATE TYPE complexity_level AS ENUM ('simple', 'moderate', 'complex', 'enterprise');
CREATE TYPE conceptual_category AS ENUM ('utility', 'productivity', 'entertainment', 'ecommerce', 'social', 'educational', 'health', 'finance', 'custom');
CREATE TYPE extensibility_model AS ENUM ('fixed_structure', 'modular_growth', 'feature_addition', 'architectural_evolution');
CREATE TYPE maintenance_strategy AS ENUM ('minimal', 'structured', 'comprehensive', 'enterprise');

CREATE TABLE architecture_plans (
    plan_id UUID PRIMARY KEY,
    project_identity_id UUID NOT NULL,
    conceptual_category conceptual_category NOT NULL,
    complexity_level complexity_level NOT NULL,
    structural_philosophy TEXT NOT NULL,

    -- Flutter-specific architecture components stored as JSONB for flexibility
    execution_model JSONB NOT NULL,
    concern_separation JSONB NOT NULL,
    state_management JSONB NOT NULL,
    file_strategy JSONB NOT NULL,
    ui_architecture JSONB NOT NULL,
    navigation_architecture JSONB NOT NULL,
    naming_conventions JSONB NOT NULL,
    performance_strategy JSONB NOT NULL,

    -- Extension and evolution policies
    extensibility_model extensibility_model NOT NULL,
    maintenance_strategy maintenance_strategy NOT NULL,

    -- Flutter platform constraints (enforced)
    platform_constraints JSONB NOT NULL DEFAULT '{"target_platform": "android", "ui_only": true, "no_backend": true, "no_networking": true, "no_databases": true}',

    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Foreign key constraint
    CONSTRAINT fk_architecture_plans_project_identity_id
        FOREIGN KEY (project_identity_id)
        REFERENCES project_identities(identity_id)
        ON DELETE CASCADE,

    -- Constraints to ensure Flutter platform compliance
    CONSTRAINT chk_platform_constraints_android CHECK (
        (platform_constraints->>'target_platform') = 'android'
    ),
    CONSTRAINT chk_platform_constraints_ui_only CHECK (
        (platform_constraints->>'ui_only')::boolean = true
    ),
    CONSTRAINT chk_platform_constraints_no_backend CHECK (
        (platform_constraints->>'no_backend')::boolean = true
    ),
    CONSTRAINT chk_platform_constraints_no_networking CHECK (
        (platform_constraints->>'no_networking')::boolean = true
    ),
    CONSTRAINT chk_platform_constraints_no_databases CHECK (
        (platform_constraints->>'no_databases')::boolean = true
    )
);

-- Indexes for performance optimization
CREATE INDEX idx_architecture_plans_project_identity_id ON architecture_plans(project_identity_id);
CREATE INDEX idx_architecture_plans_complexity ON architecture_plans(complexity_level);
CREATE INDEX idx_architecture_plans_category ON architecture_plans(conceptual_category);
CREATE INDEX idx_architecture_plans_created_at ON architecture_plans(created_at DESC);
CREATE INDEX idx_architecture_plans_extensibility ON architecture_plans(extensibility_model);

-- B-tree indexes for specific field queries
CREATE INDEX idx_architecture_plans_navigation_pattern ON architecture_plans ((execution_model->>'navigation_pattern'));
CREATE INDEX idx_architecture_plans_state_pattern ON architecture_plans ((state_management->>'primary_pattern'));
CREATE INDEX idx_architecture_plans_project_structure ON architecture_plans ((file_strategy->>'project_structure'));

-- GIN indexes for full JSONB document search and containment queries
CREATE INDEX idx_architecture_plans_execution_model_gin ON architecture_plans USING GIN (execution_model);
CREATE INDEX idx_architecture_plans_state_management_gin ON architecture_plans USING GIN (state_management);
CREATE INDEX idx_architecture_plans_file_strategy_gin ON architecture_plans USING GIN (file_strategy);
CREATE INDEX idx_architecture_plans_ui_architecture_gin ON architecture_plans USING GIN (ui_architecture);
CREATE INDEX idx_architecture_plans_navigation_architecture_gin ON architecture_plans USING GIN (navigation_architecture);

-- Enable Row Level Security
ALTER TABLE architecture_plans ENABLE ROW LEVEL SECURITY;

-- RLS Policies for architecture plans
CREATE POLICY "Users can view architecture plans" ON architecture_plans
    FOR SELECT USING (
        true  -- For now, allow all authenticated users to view
    );

CREATE POLICY "Users can insert architecture plans" ON architecture_plans
    FOR INSERT WITH CHECK (
        true  -- For now, allow all authenticated users to insert
    );

CREATE POLICY "Users can update architecture plans" ON architecture_plans
    FOR UPDATE USING (
        true  -- Allow updates for plan refinements
    );

CREATE POLICY "Users can delete architecture plans" ON architecture_plans
    FOR DELETE USING (
        true  -- Allow deletion for plan regeneration
    );

-- Add comments for documentation
COMMENT ON TABLE architecture_plans IS 'Comprehensive Flutter UI architecture plans generated by the Architecture Decision Engine';
COMMENT ON COLUMN architecture_plans.plan_id IS 'Unique identifier for the architecture plan';
COMMENT ON COLUMN architecture_plans.project_identity_id IS 'References the project identity this plan belongs to';
COMMENT ON COLUMN architecture_plans.conceptual_category IS 'High-level category of the Flutter application';
COMMENT ON COLUMN architecture_plans.complexity_level IS 'Complexity level determining architecture sophistication';
COMMENT ON COLUMN architecture_plans.structural_philosophy IS 'Overall structural approach for the Flutter app';
COMMENT ON COLUMN architecture_plans.execution_model IS 'Flutter app execution patterns and lifecycle management';
COMMENT ON COLUMN architecture_plans.concern_separation IS 'How concerns are separated in the Flutter project structure';
COMMENT ON COLUMN architecture_plans.state_management IS 'State management approach and patterns for the Flutter app';
COMMENT ON COLUMN architecture_plans.file_strategy IS 'File organization strategy and decomposition rules';
COMMENT ON COLUMN architecture_plans.ui_architecture IS 'Widget composition and UI architecture patterns';
COMMENT ON COLUMN architecture_plans.navigation_architecture IS 'Navigation and routing architecture for the Flutter app';
COMMENT ON COLUMN architecture_plans.naming_conventions IS 'Naming conventions for files, classes, and variables';
COMMENT ON COLUMN architecture_plans.performance_strategy IS 'Performance optimization strategies and patterns';
COMMENT ON COLUMN architecture_plans.extensibility_model IS 'How the architecture can evolve and extend';
COMMENT ON COLUMN architecture_plans.maintenance_strategy IS 'Maintenance approach and complexity level';
COMMENT ON COLUMN architecture_plans.platform_constraints IS 'Enforced platform constraints (Android-only, UI-only, etc.)';
