// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pjfbjfjvuwqjqyuvwriq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBqZmJqZmp2dXdxanF5dXZ3cmlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0OTQ3MjMsImV4cCI6MjA2NjA3MDcyM30.XFgL-nT1SlFkR5teBTZfcy2nPHPky4ccNNEaAmtdI0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);