
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obiornwzxtvsxpahbzcv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iaW9ybnd6eHR2c3hwYWhiemN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2OTI0OTYsImV4cCI6MjA2MjI2ODQ5Nn0.S1bCtecOUmHxWz171INdD_4XVq90onls4nh6nazIGYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Adding custom TypeScript helper to handle tables not yet in the type definition
export type CustomDatabase = Database & {
  public: {
    Tables: {
      campaign_variants: {
        Row: {
          id: string;
          campaign_id: string;
          variant_name: string;
          template_id: string;
          distribution_percentage: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          campaign_id: string;
          variant_name: string;
          template_id: string;
          distribution_percentage?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          campaign_id?: string;
          variant_name?: string;
          template_id?: string;
          distribution_percentage?: number;
          created_at?: string;
        };
      };
      security_logs: {
        Row: {
          id: string;
          user_id?: string;
          event_type: string;
          event_level: string;
          message: string;
          details?: any;
          user_agent?: string;
          location?: string;
          ip_address?: string;
          is_anomalous: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          event_type: string;
          event_level: string;
          message: string;
          details?: any;
          user_agent?: string;
          location?: string;
          ip_address?: string;
          is_anomalous?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          event_type?: string;
          event_level?: string;
          message?: string;
          details?: any;
          user_agent?: string;
          location?: string;
          ip_address?: string;
          is_anomalous?: boolean;
          created_at?: string;
        };
      };
      security_anomalies: {
        Row: {
          id: string;
          user_id?: string;
          event_data: any;
          reasons: string[];
          user_agent?: string;
          location?: string;
          ip_address?: string;
          detected_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          event_data: any;
          reasons: string[];
          user_agent?: string;
          location?: string;
          ip_address?: string;
          detected_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          event_data?: any;
          reasons?: string[];
          user_agent?: string;
          location?: string;
          ip_address?: string;
          detected_at?: string;
        };
      };
    } & Database['public']['Tables'];
  };
};

// Create a type-augmented client
export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
